### ISSUE TITLE
API v0.1.24 not compatible with C* 4.0-rc1

### ISSUE THREAD

**Issue by grighetto** [k8ssandra/management-api-for-apache-cassandra#103]
Running the API with a custom C* build off the `cassandra-4.0-rc1` tag (3282f5ecf187ecbb56b8d73ab9a9110c010898b0) fails with:

```
ERROR [nioEventLoopGroup-3-11] 2021-04-26 14:58:34,013 NodeOpsResources.java:339 - Error when executing request
com.datastax.oss.driver.api.core.servererrors.ServerError: Failed to execute method NodeOps.checkConsistencyLevel
	at com.datastax.oss.driver.api.core.servererrors.ServerError.copy(ServerError.java:54)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
	at com.datastax.mgmtapi.CqlService.executePreparedStatement(CqlService.java:70)
	at com.datastax.mgmtapi.resources.K8OperatorResources.lambda$checkClusterConsistency$1(K8OperatorResources.java:93)
	at com.datastax.mgmtapi.resources.NodeOpsResources.handle(NodeOpsResources.java:331)
	at com.datastax.mgmtapi.resources.K8OperatorResources.checkClusterConsistency(K8OperatorResources.java:83)
```

**Comment by emerkle826** [comment]
The fix for this is likely going to need to include a driver upgrade (likely 4.11.1) that has a fix for [JAVA-2936](https://datastax-oss.atlassian.net/browse/JAVA-2936)
